// Local QA only. See docs/validation/production-design-refinement.md for prerequisites.
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.connectOverCDP(process.env.DESIGN_CDP);
const context = browser.contexts()[0];
const page = context.pages().find(p => p.url().startsWith('http://localhost:3000'));
assert(page, 'Open an authenticated local Insieme browser first');
const output = 'docs/validation/production-design';
mkdirSync(output, { recursive: true });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const pause = () => page.waitForTimeout(250);
const checkOverflow = async p => assert(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${p.viewportSize()?.width}`);
await page.setViewportSize({width:1440,height:1000});
await page.emulateMedia({colorScheme:'light'});
await page.getByRole('link',{name:'Discover',exact:true}).click();
await page.locator('#film-search').fill('matrix');
await page.getByRole('button',{name:'Search',exact:true}).first().click();
await page.locator('.discovery-card').first().waitFor({timeout:90000});
assert.equal(await page.locator('.search-results').first().evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),6);
await page.evaluate(()=>window.scrollTo(0,480)); await pause();
const scroll = await page.evaluate(()=>scrollY);
await page.getByRole('link',{name:'Watchlist',exact:true}).click(); await pause();
await page.getByRole('link',{name:'History',exact:true}).click(); await pause();
await page.goBack(); await pause();
assert.equal(new URL(page.url()).searchParams.get('view'),'watchlist');
await page.goBack(); await pause();
assert.equal(await page.locator('#film-search').inputValue(),'matrix');
assert(Math.abs(await page.evaluate(()=>scrollY)-scroll)<5,'Discovery scroll restored');
await page.goForward(); await pause();
assert.equal(new URL(page.url()).searchParams.get('view'),'watchlist');
await page.getByRole('link',{name:'Discover',exact:true}).click();
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:`${output}/desktop-light.png`,fullPage:true});
await checkOverflow(page);
const card = page.locator('.discovery-card').filter({has:page.getByRole('button',{name:'View details for The Matrix Reloaded',exact:true})});
const add = card.locator('.result-actions button');
await page.mouse.move(0,0); await page.locator('#film-search').focus(); await pause();
assert.equal(await add.evaluate(e=>getComputedStyle(e).opacity),'0');
await card.locator('.result-details-trigger').focus(); await pause();
assert.equal(await add.evaluate(e=>getComputedStyle(e).opacity),'1');
const before = await card.boundingBox();
await card.hover(); await pause();
assert.deepEqual(await card.boundingBox(),before,'Hover does not shift card');
await page.route('**/api/watchlist',route=>route.request().method()==='POST'?route.abort():route.continue());
await add.click();
await card.getByRole('alert').waitFor();
assert.equal(await page.locator('dialog[open]').count(),0,'Add does not open details');
await page.unroute('**/api/watchlist');
await add.click();
await page.getByRole('button',{name:'In Watchlist: The Matrix Reloaded',exact:true}).waitFor();
await page.getByRole('link',{name:'Watchlist',exact:true}).click();
await page.getByRole('button',{name:'View details for The Matrix Reloaded',exact:true}).click();
await page.getByRole('button',{name:'Remove from Watchlist',exact:true}).click();
await page.getByRole('button',{name:'Undo',exact:true}).click();
await page.getByRole('button',{name:'View details for The Matrix Reloaded',exact:true}).waitFor();
await page.getByRole('button',{name:'Pick a film',exact:true}).click();
await page.locator('dialog[open]').waitFor();
await page.keyboard.press('Escape');
assert.equal(await page.locator('dialog[open]').count(),0);
await page.getByRole('button',{name:'View details for The Matrix Reloaded',exact:true}).click();
await page.getByRole('button',{name:'Mark as watched',exact:true}).click();
await page.getByRole('link',{name:'History',exact:true}).click();
await page.getByRole('button',{name:'View details for The Matrix Reloaded',exact:true}).waitFor();
await page.getByRole('link',{name:'Discover',exact:true}).click();
await page.getByRole('button',{name:'Watched: The Matrix Reloaded',exact:true}).waitFor();
await page.getByRole('link',{name:'Design QA',exact:true}).click();
await page.locator('#theme').selectOption('dark');
await page.reload();
assert.equal(await page.locator('#theme').inputValue(),'dark');
assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(20, 28, 40)');
await page.getByRole('link',{name:'Back to Watchlist'}).click();
await page.locator('#film-search').fill('matrix');
await page.getByRole('button',{name:'Search',exact:true}).first().click();
await page.locator('.discovery-card').first().waitFor({timeout:90000});
await page.screenshot({path:`${output}/desktop-dark.png`,fullPage:true});
await checkOverflow(page);
const storageState = await context.storageState();
const mobile = await browser.newContext({storageState,viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
const phone = await mobile.newPage();
phone.on('pageerror',error=>errors.push(error.message));
await phone.goto('http://localhost:3000');
await phone.locator('#film-search').fill('matrix');
await phone.getByRole('button',{name:'Search',exact:true}).first().click();
await phone.locator('.discovery-card').first().waitFor({timeout:90000});
for (const width of [390,320]) {
  await phone.setViewportSize({width,height:844});
  for(const theme of ['dark','light']) {
    await phone.evaluate(t=>{localStorage.setItem('insieme-theme',t);document.documentElement.dataset.theme=t},theme);
    await checkOverflow(phone);
    assert.equal(await phone.locator('.search-results').first().evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),2);
    assert.equal(await phone.locator('.result-actions button').first().evaluate(e=>getComputedStyle(e).opacity),'1');
    await phone.screenshot({path:`${output}/mobile-${width}-${theme}.png`,fullPage:true});
  }
}
await phone.getByRole('button',{name:'Filters',exact:true}).click();
await checkOverflow(phone);
await phone.screenshot({path:`${output}/mobile-filters.png`});
await phone.getByRole('button',{name:'Close filters'}).click();
await phone.getByRole('button',{name:'Current Watchlist:',exact:false}).click();
await checkOverflow(phone);
await phone.screenshot({path:`${output}/mobile-watchlists.png`});
await phone.getByRole('button',{name:'Close Watchlist manager'}).click();
await phone.emulateMedia({reducedMotion:'reduce'});
assert.equal(await phone.locator('.result-actions button').first().evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
await mobile.close();
assert.deepEqual(errors,[]);
console.log('PASS: navigation/history/scroll, desktop hover/focus, failed add/retry, add/remove/Undo, picker, watched history, theme persistence, mobile 390/320 both themes, sheets, reduced motion, overflow, no page errors');
await browser.close();
